# Generated by Django 3.0.5 on 2021-04-28 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
