# Generated by Django 3.0.5 on 2021-04-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsitem_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
